USE [CarRigister]

CREATE TABLE Persons(
	PERSON_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	MIDDLE_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30) NOT NULL,
	UNIQUE(FIRST_NAME, MIDDLE_NAME, LAST_NAME),
	PHONE VARCHAR(20),
)

CREATE TABLE CarNames(
	CAR_NAME_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CAR_NAME VARCHAR(30),
)

CREATE TABLE CarModels(
	CAR_MODEL_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CAR_NAME_ID INT NOT NULL,
	CAR_MODEL VARCHAR(30) NOT NULL,
	FOREIGN KEY (CAR_NAME_ID) REFERENCES CarNames(CAR_NAME_ID), 
)

CREATE TABLE Cars(
	CAR_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PERSON_ID INT NOT NULL,
	CAR_NUMBER VARCHAR(20),
	CAR_MODEL_ID INT NOT NULL,
	UNIQUE(CAR_NUMBER),
	FOREIGN KEY (PERSON_ID) REFERENCES Persons(PERSON_ID),
	FOREIGN KEY (CAR_MODEL_ID) REFERENCES CarModels(CAR_MODEL_ID)
)

